---
- name: cloning
  hosts: all
  tasks:
    - name: insatll git
      apt:
        name: git
        state: present
        update_cache: true
    - name: copy
      git:
        repo: git@github.com:MSunaina/Ansible.git
        dest: . 
        clone: yes
        update: yes
