---
- name: cloning
  hosts: all
  tasks:
    - name: insatll git
      apt:
        upgrade: yes
        name: git
        state: present
        update_cache: yes
    - name: copy
      git:
        repo: https://github.com/MSunaina/Ansible.git
        dest: . 
        clone: yes
        update: yes
