---
- name: cloning
  hosts: all
  tasks:
    - name: insatll git
      yum:
        name: git
        state: present
    - name: copy
      git:
        repo: git@github.com:MSunaina/Ansible.git
        dest: . 

