---
- name: cloning
  hosts: all
  tasks:
    - name: copy
      git:
        repo: https://github.com/MSunaina/Ansible.git
        dest: /home/ansibleuser/github
        clone: yes
        update: yes
