---
- name: cloning
  hosts: all
  become: yes 
  tasks:
    - name: copy
      git:
        repo: https://github.com/MSunaina/Ansible.git
        dest: /home/ansibleuser/sam
        clone: yes
        update: yes
